# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Replicator < Formula
  desc ""
  homepage ""
  version "0.20.0"

  on_macos do
    url "https://github.com/pivotal-cf/replicator/releases/download/0.20.0/replicator-darwin.tar.gz"
    sha256 "9811687b17a8cd232bd4a17b4d538e105f4e99ef30b02039a05420c22c139103"

    define_method(:install) do
      bin.install "replicator"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Replicator
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pivotal-cf/replicator/releases/download/0.20.0/replicator-linux.tar.gz"
      sha256 "618257002af41697a15f5f25eb0cdb4582de89d7469ba9e10fa42cbc796ed03b"
      define_method(:install) do
        bin.install "replicator"
      end
    end
  end

  test do
    system "#{bin}/replicator --version"
  end
end
