# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Replicator < Formula
  desc ""
  homepage ""
  version "0.14.0"

  on_macos do
    url "https://github.com/pivotal-cf/replicator/releases/download/0.14.0/replicator-darwin.tar.gz"
    sha256 "254905bac05bf1ce166a8736a10702d1f5947b3c3af1e0b4e8ac92ac655fab71"

    def install
      bin.install "replicator"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Replicator
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pivotal-cf/replicator/releases/download/0.14.0/replicator-linux.tar.gz"
      sha256 "a3dda7d940f955a061c28b830e84e53fcf23bac4b2c6589cfd55cd9179096c16"

      def install
        bin.install "replicator"
      end
    end
  end

  test do
    system "#{bin}/replicator --version"
  end
end
