# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Replicator < Formula
  desc ""
  homepage ""
  version "0.12.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pivotal-cf/replicator/releases/download/0.12.0/replicator-darwin.tar.gz"
      sha256 "4eda65e0cc8952bedd9902e21b5618b12eaeeaf49a6b109c6dacadd3e6d4e9e4"

      def install
        bin.install "replicator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pivotal-cf/replicator/releases/download/0.12.0/replicator-linux.tar.gz"
      sha256 "2857e09c36781ce8e4e940f8e791e631dbbf7bee41661905f48c9bb3a069f3ac"

      def install
        bin.install "replicator"
      end
    end
  end

  test do
    system "#{bin}/replicator --version"
  end
end
