version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  target-branch: "master"
  schedule:
    interval: "weekly"

- package-ecosystem: "gomod"
  directory: "/"
  target-branch: "master"
  schedule:
    interval: "weekly"
