name: ci

on:
  workflow_dispatch:
  push:
    branches:
    - "master"
    tags:
    - "*"
  pull_request:

permissions:
  contents: write

jobs:
  test-and-release:
    name: Test and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: ./go.mod

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test --covermode=atomic --coverprofile=replicator-${{ github.sha }}-unit-test-code-coverage.out -v ./...

      - name: Archive Unit Test Code Coverage Output
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7
        with:
          name: Unit Test Code Coverage Output
          path: replicator-${{ github.sha }}-unit-test-code-coverage.out
          overwrite: true

      - if: startsWith(github.ref, 'refs/tags/')
        name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - if: startsWith(github.ref, 'refs/tags/')
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
